services:
  dataset-processing:
    extends:
      file: docker-compose.yml
      service: dataset-processing

  curt-mini-icnf:
    extends:
      file: docker-compose.yml
      service: curt-mini-icnf

  curt-mini-icnf-bag-play:
    extends:
      file: docker-compose.yml
      service: curt-mini-icnf-bag-play

  curt-mini-icnf-gpu:
    extends:
      file: docker-compose.yml
      service: curt-mini-icnf-gpu

  sensor-fusion-ros-gui:
    extends:
      file: docker-compose.yml
      service: sensor-fusion-ros-gui
